#!/usr/bin/python
with open ("annotation.txt", "r") as annotation:
    anotation_dict = {}
    for line in annotation:
        line = line.split()
        if line: #test whether it is an empty line
            anotation_dict[line[0]]=line[1:]
        else:
            continue

ofile = open ("toutput.fasta", "w")

with open ("test", "r") as myfasta:
    for line in myfasta:
        if line.startswith (">"):
            line = line[1:] # skip the ">" character
            line = line.split()
            if line[0] in anotation_dict:
                new_line = ">" + str(line[0]) + " " + " ".join(anotation_dict[line[0]])
                ofile.write ( new_line + "\n")
        else:
            ofile.write(line)
